name: CI/CD - GitHub Marketplace Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: 1 - Checkout do código
        uses: actions/checkout@v4

      - name: 2 - Configurar ambiente .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências da aplicação
        run: dotnet restore MarketplaceActionsDemo.csproj

      - name: Restaurar dependências dos testes
        run: dotnet restore MarketplaceActionsDemo.Tests/MarketplaceActionsDemo.Tests.csproj

      - name: Compilar aplicação
        run: dotnet build MarketplaceActionsDemo.csproj --configuration Release --no-restore

      - name: Compilar projeto de testes
        run: dotnet build MarketplaceActionsDemo.Tests/MarketplaceActionsDemo.Tests.csproj --configuration Release --no-restore

      - name: Executar testes
        run: dotnet test MarketplaceActionsDemo.Tests/MarketplaceActionsDemo.Tests.csproj --configuration Release --no-build

      - name: 3 - Construir imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: marketplace-actions-demo:latest
